server.port=8084

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/AdmissionDB
spring.datasource.username=postgres
spring.datasource.password=#Thanos2502
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Correct property to point the Eureka Client to the Eureka Server
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
